services:
  # Backend API Service
  - type: web
    name: meme-generator-api
    env: python
    plan: free
    region: ohio
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    runtime: python3.9
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9
      - key: FIREBASE_CREDENTIALS_PATH
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false

  # Frontend Static Site
  - type: web
    name: meme-generator-frontend
    env: static
    plan: free
    region: ohio
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_HOST
        fromService:
          name: meme-generator-api
          type: web
          property: host
      - key: REACT_APP_API_PORT
        fromService:
          name: meme-generator-api
          type: web
          property: port
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
